%% \ducted_prop_thrust.m  
%  \brief:  A function that calculates total thrust of a ducted propeller. 
%   It generates a vector with total thrust and shroud thrust as output.
%  \author: Claudio Mirabella, Christian Salzano
%  \version: 1.04
%
% Eli-TAARG is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public
% License as published by the Free Software Foundation; either
% version 3 of the License, or (at your option) any later version.
%
% Eli-TAARG is developed by the TAARG Educational organization for
% educational purposes only.
% Theoretical and Applied Aerodynamic Research Group - University of Naples Federico II.
%
% Eli-TAARG GitHub link: <https://github.com/TAARG-Education/Eli-TAARG>
%
% Eli-TAARG is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
% General Public License for more details.
% <http://www.gnu.org/licenses/>.
%
% ==============================================================================================
% |Name        : ducted_prop_thrust.m                                                        |
% |Author      : Claudio Mirabella, Christian Salzano                                    |
% |              University of Naples Federico II.                                       |
% |Version     : 1.04                                                                    |
% |Date        : 25/11/2020                                                              |
% |Modified    : 18/02/2021                                                              |
% |Description : A function that calculates total thrust of a ducted propeller.          | 
% |              It generates a vector with total thrust and shroud thrust as output.    |     
% |Reference   : Lezioni di Aerodinamica dell'Ala Rotante                                |                                                         
% |Input       :                                                                         |
% |              (rho) = Density                                                         |
% |              (ch) = Chord of the shroud                                              |  
% |              (Vinf) = Stream velocity                                                |
% |              (D14) = Shroud diameter at c/4                                          |
% |              (D34) = Shroud diameter at 3c/4                                         |
% |              (theta) = Angle of tangent between velocity and mean
%                          camber line at 3c/4
% |              (R) = Rotor radius                                                      |
% |              (TR) = Isolated rotor thrust                                            |
% |Output      : (T) = Total thrust generated                                            |
% |              (TS) = Thrust generated by the shroud                                   |
% |Note        :                                                                         |
% ==============================================================================================

function [T, TS] = ducted_prop_thrust(rho, ch, Vinf, D14, D34, theta, R, TR)
% Use function Feature_RVortexInt to evaluate universal function f
f = Feature_RvortexInt(ch,D14,D34);
% ---------------------------------------------------------------------
% Propeller's induced velocity calculations
% eq 4.24 
w0 = .5*(-Vinf + sqrt(Vinf^2 + 2*TR/(rho*pi*R^2)));  
% ---------------------------------------------------------------------
% Elicoidal vortex induced axial velocity at 3c/4
% eq 3.15
w34 = w0*[1 + (0.75*ch/R)/sqrt(1+(0.75*ch/R)^2)];
% ---------------------------------------------------------------------
% Rotor's induced radial velocity at 3c/4
% eq 4.23
vi34 = -0.5*(D34/2)*w0*(R^2/((R^2 + (0.25*ch)^2)^1.5));
% ---------------------------------------------------------------------
% Anular vortex induced velocity calculated using tangency condition at
% 3c/4
% eq 4.25
vi = -vi34 - theta*(w34 + Vinf);
% ---------------------------------------------------------------------
% Circulation around the shroud 
% eq. 4.26
Gamma = (pi*D14/f)*[-vi34 - theta*(Vinf + w34)];
% ---------------------------------------------------------------------
% Rotor's induced radial velocity at c/4
% eq 4.23
vi14 = -0.5*(D14/2)*w0*(R^2/((R^2 + (-0.25*ch)^2)^1.5));
% ---------------------------------------------------------------------
% Thrust component due to the shroud
TS = -rho*vi14*Gamma*pi*D14;
% ---------------------------------------------------------------------
% Total thrust
T = TR + TS;
% ---------------------------------------------------------------------
end
