% ---------------------------------------------------------------------
% FUNCTION NAME: elica_intubata
%   A function that calculates total thrust of a ducted propeller. 
%   It generates a vector with total thrust and shroud thrust as output.
%   INPUT
%   1 ---> rho      : Density
%          Type     : Float
%   2 ---> Gamma    : Ring vortex circulation associated with the shroud
%          Type     : Float
%   3 ---> Vinf     : Stream velocity
%          Type     : Float
%   4 ---> Dquarter : Shroud diameter at c/4
%          Type     : Float
%   5 ---> R        : Shroud radius 
%          Type     : Float
%   6 ---> TR       : Isolated rotor thrust
%          Type     : Float
%   OUTPUT
%   1 ---> T        : Total thrust generated 
%          Type     : Float
%   2 ---> TS       : Thrust generated by the shroud
%          Type     : Float
% ---------------------------------------------------------------------
function [T, TS] = elica_intubata(rho, Gamma, Vinf, Dquarter, R, TR)
% ---------------------------------------------------------------------
% Propeller's induced velocity calculations
%  eq 4.24
w0 = .5*(-Vinf + sqrt(Vinf^2 + 2*TR/(rho*pi*R^2)));
% ---------------------------------------------------------------------
% Streamtube's radius rt calculated via the continuity
%  eq 4.20
A = pi*R^2;
const=0;
const = (Vinf + w0)*A;
rt = sqrt(const/(Vinf*pi));
% ---------------------------------------------------------------------
% Radial velocity component induced by the rotor at c/4
%  eq 4.23
cquarter=1/4;
viRquarter = -.5*rt*w0*R^2/((R^2+cquarter^2)^1.5);
% ---------------------------------------------------------------------
% Thrust component due to the shroud
TS = -rho*viRquarter*Gamma*pi*Dquarter;
% ---------------------------------------------------------------------
% Total thrust
T = TR + TS;
% ---------------------------------------------------------------------
end
